config/routes.rb
Rails.application.routes.draw do
  get 'albums/new'
  post 'albums/create'
  get 'albums/index'
  get 'albums/show'
  get 'albums/update'
  get 'albums/destroy'
  get 'bands/new'
  post 'bands/create'
  get 'bands/index'
  get 'bands/show'
  get 'bands/update'
  get 'bands/destroy'
  get 'index/index'
  post 'songs/create'
  get 'songs/index'
  get 'songs/show'
  get 'songs/update'
  get 'songs/destroy'

  resources :songs

resources :albums do
  resources :songs
end

resources :bands do
  resources :albums
end
  root 'index#index'
  #mount Songs::SongsAPI => '/api/songs'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
	has_many :songs
    belongs_to :band
    validates :title, length: { minimum: 2 }
    
    def self.search(term,page)
	    if term
	      where('name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
	    else
	      paginate(page: page, per_page: 10).order('id DESC')
	    end
	  end
	  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
	has_many :albums
	validates :name, length:{ minimum: 2 }
	validates :name,:date_created,:photo, presence: true
	 def self.search(term,page)
	    if term
	      where('name LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
	    else
	      paginate(page: page, per_page: 10).order('id DESC')
	    end
	  end
end

app/models/song.rb
class Song < ApplicationRecord
 	belongs_to :album
 	validates :title,:length, length: { minimum: 2 }
	validates :title,:length, presence: true
	validates :title, length: { maximum: 50 , too_long: "%{count} characters is the max allowed."}
	validates :length, format: { with: /[0-9][0-9]:[0-5][0-9]/, message: "Format is MM:SS - only digits."}
	#validates :length, numericality: { only_integer: true }
	  def self.search(term,page)
	    if term
	      where('title LIKE ?', "%#{term}%").paginate(page: page, per_page: 5).order('id DESC')
	    else
	      paginate(page: page, per_page: 10).order('id DESC')
	    end
	  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    #@albums = album.all
    @albums = Album.search(params[:term], params[:page])
  end

  def show
    @album = Album.find(params[:id])
    @songs = Song.where(album: @album)   
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = 'album added.'
      redirect_to albums_path
    else
      flash[:error] = 'Failed to add the album!'
      render :new
    end
    #reder json: @album, status: :created
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      flash[:notice] = 'album updated.'
      redirect_to albums_path
    else
      flash[:error] = 'Failed to update the album!'
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to action:"index"
  end

  private

  def album_params
    params.require(:album).permit(:title, :premiere_date, :band_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def index
	end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    #@bands = band.all
    @bands = Band.search(params[:term], params[:page])
  end

  def show
    @bands = Band.find(params[:id])
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:notice] = 'band added.'
      redirect_to bands_path
    else
      flash[:error] = 'Failed to add that band!'
      render :new
    end
    #reder json: @band, status: :created
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      flash[:notice] = 'band updated.'
      redirect_to bands_path
    else
      flash[:error] = 'Failed to update the band!'
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to action:"index"
  end

  private

  def band_params
    params.require(:band).permit(:name, :date_created, :photo)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    #@songs = Song.all
    @songs = Song.search(params[:term], params[:page])
  end

  def show
    @song = Song.find(params[:id])
   
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:notice] = 'Song added.'
      redirect_to songs_path
    else
      flash[:error] = 'Failed to add the song!'
      render :new
    end
    #reder json: @song, status: :created
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(song_params)
      flash[:notice] = 'Song updated.'
      redirect_to songs_path
    else
      flash[:error] = 'Failed to update the song!'
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to action:"index"
  end

  private

  def song_params
    params.require(:song).permit(:title, :length, :lyrics, :album_id)
  end
end

app/controllers/v1/songs_controller.rb
class V1::SongsController < ApplicationController
  def index
    @songs = Song.all

    render json: @songs, status: :ok
  end

  def show
    @songs = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:notice] = 'Song added.'
      redirect_to root_path
    else
      flash[:error] = 'Failed to add the song!'
      render :new
    end
    #reder json: @song, status: :created
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(product_params)
      flash[:notice] = 'Song updated.'
      redirect_to root_path
    else
      flash[:error] = 'Failed to update the song!'
      render :edit
    end
  end

  def delete
    @song = Song.where(id: params[:id]).first
    if @song.delete
      head(:ok)
    else
      head(:unprocessable_entity)
    end
  end

  private

  def song_params
    params.require(:song).permit(:author, :album, :name, :length)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/v1/songs_helper.rb
module V1::SongsHelper
end

app/views/albums/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

app/views/albums/edit.html.erb
<div class="modal-content">
  <%= form_for @album, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Edit album</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@album.errors.full_messages.first}</div>".html_safe if @album.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">albums title</label>
              <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Premiere date</label>
              <%= f.date_field  :premiere_date, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Band</label>
            
                <%= f.collection_select :band_id, Band.order(:name), :id, :name, {}, { class: "form-control" } %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'albums', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;' %>
        <%= f.submit 'Edit album', class: "btn btn-primary", style: 'border-radius: 0px;' %>
      </div>
  <% end %>
</div>

app/views/albums/index.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title" style="color: #286090; text-align: center;">Albums</h4>
  </div>
  <%= form_tag(albums_path, method: :get) do %>
  <div class="form-container"> 
    <%= text_field_tag :term, params[:term], class: 'form-control form-ctr' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary btn-nav', style: 'width: 9.5%'  %> 
  </div>
  <% end %>

   
  <div class="modal-body">  
    <hr class="hr-st">
    <%= link_to 'Add album', new_album_path, class: 'btn btn-success btn-scs'%>

    <hr class="hr-st">
     <table id="albums" class="display" cellspacing="0" width="100%">
      <tr>
        <th>Title</th>
        <th>Premiere </th>
        <th>Band name </th>
      </tr>
    <tr>
  <% for album in @albums %>
              <td><%= album.title %></td>
              <td><%= album.premiere_date.to_time.strftime('%d - %m - %Y') %></td>      
              <td><%= album.band.name %></td>                  
          <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_album_path(album), class: 'btn btn-success', style: 'border-radius: 0px;' %>
                <%= link_to 'Show',album_path(album), class: 'btn btn-primary', style: 'border-radius: 0px;' %>
                <%= link_to 'Delete', album_path(album), method: :delete, class: 'btn btn-danger',  data:{ confirm: 'Are you sure?'}, style: 'border-radius: 0px;' %>
              </div>
          </td>
      </tr>
  <% end %>
</table>
  </div>
  <div class="apple_pagination">
  <div class="">
    <%= page_entries_info @albums %>
  </div>
  <%= will_paginate @albums, :container => false %>
</div>

</div>

app/views/albums/new.html.erb
<div class="modal-content">
  <%= form_for @album, url: {action: :create} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add album</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@album.errors.full_messages.first}</div>".html_safe if @album.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">albums title</label>
              <%= f.text_field :title, class: "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Premiere date</label>
              <%= f.date_field  :premiere_date, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Band</label>              
               
                <%= f.collection_select :band_id, Band.order(:name), :id, :name, {}, { class: "form-control" } %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'albums', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>
        <%= f.submit 'Create album', class: "btn btn-primary", style: 'border-radius: 0px;' %>
      </div>
  <% end %>
</div>

app/views/albums/show.html.erb
<div class="modal-content">
  <div class="modal-body">
  	<h2 style="text-align: center; color:#286090;">Album details</h2>
  	 <hr class="hr-st">
 Title
   <h2><%= @album.title %></h2>
	<hr>
	Premiere Date
   <h2><%= @album.premiere_date %></h2>
   <hr>
   <p>Band</p>
   <h2><%= @album.band.name %></h2>
   <hr class="hr-st">
   Songs:
   <% @x = 0 %>
   <% for song in @songs %>
   <h4><%= @x = @x + 1 %><%= "." %> <%= song.title %></h4>
   <%end%>          
<hr class="hr-st">

 <div class="modal-footer">
        <%= link_to 'Back', { controller: 'albums', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>        
      </div>
         

  </div>
</div>

app/views/albums/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

app/views/bands/edit.html.erb
<div class="modal-content">
  <%= form_for @band, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Edit band</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@band.errors.full_messages.first}</div>".html_safe if @band.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Bands name</label>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Date created</label>
              <%= f.date_field  :date_created, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Photo</label>
              <%= f.text_field:photo, class: "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'bands', action: 'index'}, class: 'btn btn-default',  style: 'border-radius: 0px;'%>
        <%= f.submit 'Update band', class: "btn btn-primary", style: 'border-radius: 0px;' %>
      </div>
  <% end %>
</div>

app/views/bands/index.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title" style="color: #286090; text-align: center;">Bands</h4>
  </div>
  <%= form_tag(bands_path, method: :get) do %>
  <div class="form-container"> 
    <%= text_field_tag :term, params[:term], class: 'form-control form-ctr' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary btn-nav', style: 'width: 9.5%'  %> 
  </div>
  <% end %>

   
  <div class="modal-body">  
    <hr class="hr-st">
    <%= link_to 'Add band', new_band_path, class: 'btn btn-success btn-scs'%>

    <hr class="hr-st">
     <table id="bands" class="display" cellspacing="0" width="100%">
      <tr>
        <th>Name</th>
        <th> Date Created </th>
        <th> Photo </th>
      </tr>
       <tr>
  <% for band in @bands %>
              <td><%= band.name %></td>
              <td><%= band.date_created.to_time.strftime('%d - %m - %Y') %></td>
              <td><img width="200" src="<%= band.photo %>"/></td>           
          <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_band_path(band), class: 'btn btn-success', style: 'border-radius: 0px' %>
                <%= link_to 'Delete', band_path(band), method: :delete, class: 'btn btn-danger',  data:{ confirm: 'Are you sure?'}, style: 'border-radius: 0px' %>
              </div>
          </td>
      </tr>
  <% end %>
</table>
  </div>
  <div class="apple_pagination">
  <div class="">
    <%= page_entries_info @bands %>
  </div>
  <%= will_paginate @bands, :container => false %>
</div>

</div>

app/views/bands/new.html.erb
<div class="modal-content">
  <%= form_for @band, url: {action: :create} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add band</h4>
      </div>
      <div class="modal-body">
        <p>
          <%= "<div class=\"alert alert-danger\">#{@band.errors.full_messages.first}</div>".html_safe if @band.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-8">
              <label class="control-label">Bands name</label>
              <%= f.text_field :name, class: "form-control" %>
            </div>

            <div class="col-xs-4">
              <label class="control-label">Date created</label>
              <%= f.date_field  :date_created, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Photo</label>
              <%= f.text_field:photo, class: "form-control" %>
            </div>
          </div>
        </div>

        </p>
      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'bands', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>
        <%= f.submit 'Create band', class: "btn btn-primary", style: 'border-radius: 0px;' %>
      </div>
  <% end %>
</div>

app/views/index/index.html.erb
  


<div class="modal-content">  

<div class="modal-body">
  <h2 style="text-align: center; color:#286090;">Welcome to Music Library</h2>
     <hr class="hr-st">


  <h4 style="text-align: center; color:#286090;">You are on Home Page. </h4>
     <hr class="hr-st">
<p style="text-align: right; color:#286090;"><i>Mikołaj Bronk, Wiktor Przybyłowski</i></p>

</div>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top nav-msc">  
      <%= link_to "Music library", root_path, class:'brand' %>    
     
      <div style="float: right; margin-right: 10px; margin-top: 8px;">
          <%= link_to 'Songs', songs_path, class: 'btn btn-primary btn-nav' %>
          <%= link_to 'Albums', albums_path, class: 'btn btn-primary btn-nav' %>
          <%= link_to 'Bands', bands_path, class: 'btn btn-primary btn-nav' %>
      </div>

      
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <body style="background-image: url(http://voky.com.ua/showcase/sky-forms/examples/img/bg-red.jpg)">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>
          <%= render "layouts/header" %>
          <%= yield %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %>
    </body>
    </html>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/destroy.html.erb
<th>LOLOLOLOL</th>

app/views/songs/edit.html.erb
<div class="modal-content">
  <%= form_for @song, url: {action: :update} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Edit Song</h4>
      </div>
      <div class="modal-body">   
        <p>
          <%= "<div class=\"alert alert-danger\">#{@song.errors.full_messages.first}</div>".html_safe if @song.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Album</label>
              <%= f.collection_select :album_id, Album.order(:title), :id, :title, {}, { class: "form-control" } %>
            </div>
          </div>
       </div>
         
        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Title</label>
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Length</label>
              <%= f.text_field :length, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Lyrics</label>
              <%= f.text_area :lyrics, class: "form-control" %>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'songs', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>
        <%= f.submit 'Edit Song', class: "btn btn-primary" , style: 'border-radius: 0px;'%>
      </div>
  <% end %>
</div>

app/views/songs/index.html.erb
<div class="modal-content">
  <div class="modal-header">
    <h4 class="modal-title" style="color: #286090; text-align: center;">Songs</h4>
  </div>
  <%= form_tag(songs_path, method: :get) do %>
  <div class="form-container"> 
    <%= text_field_tag :term, params[:term], class: 'form-control form-ctr' %>
    <%= submit_tag 'Search', name: nil, class: 'btn btn-primary btn-nav', style: 'width: 9.5%'  %> 
  </div>
  <% end %>

   
  <div class="modal-body">  
    <hr class="hr-st">
    <%= link_to 'Add Song', new_song_path, class: 'btn btn-success btn-scs'%>

    <hr class="hr-st">
    <table id="songs" class="display" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th>Album</th>
        <th>Title</th>
        <th>Lyrics</th>
        <th>Length</th>
      </tr>
      </thead>
      <tbody>
            <% for song in @songs %>              
               <td><%= link_to song.album.title, song.album %></td>
              <td><%= song.title %></td>
              <td><%= song.lyrics %></td>
              <td><%= truncate(song.length) %></td>
          <td>
              <div class="btn-group">
                <%= link_to 'Edit', edit_song_path(song), class: 'btn btn-success', style: 'border-radius: 0px;' %>
                 <%= link_to 'Show', song_path(song), class: 'btn btn-primary' %>
                <%= link_to 'Delete', song_path(song), method: :delete, class: 'btn btn-danger',  data:{ confirm: 'Are you sure?'} , style: 'border-radius: 0px;' %>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="apple_pagination">
  <div class="">
    <%= page_entries_info @songs %>
  </div>
  <%= will_paginate @songs, :container => false %>
</div>

</div>

app/views/songs/new.html.erb
<div class="modal-content">
  <%= form_for @song, url: {action: :create} do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Add Song</h4>
      </div>
      <div class="modal-body">   
        <p>
          <%= "<div class=\"alert alert-danger\">#{@song.errors.full_messages.first}</div>".html_safe if @song.errors.any? %>
        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Album</label>
              <%= f.collection_select :album_id, Album.order(:title), :id, :title, {}, { class: "form-control" } %>
            </div>
          </div>
       </div>
         
        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Title</label>
              <%= f.text_field :title, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Length</label>
              <%= f.text_field :length, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-xs-12">
              <label class="control-label">Lyrics</label>
              <%= f.text_area :lyrics, class: "form-control" %>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <%= link_to 'Back', { controller: 'songs', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>
        <%= f.submit 'Create Song', class: "btn btn-primary" , style: 'border-radius: 0px;'%>
      </div>
  <% end %>
</div>

app/views/songs/show.html.erb
<div class="modal-content">
  <div class="modal-body">
  	<h2 style="text-align: center; color:#286090;">Song details</h2>
  	 <hr class="hr-st">
    Title
   <h2><%= @song.title %></h2>
	<hr>

	<p>Album</p>
   <h2><%= @song.album.title %></h2>
   <hr> 
	Lyrics 
   <h2><%= @song.lyrics %></h2>
   <hr>
   Length
   <h2><%= @song.length %></h2>
<hr class="hr-st">

 <div class="modal-footer">
        <%= link_to 'Back', { controller: 'songs', action: 'index'}, class: 'btn btn-default', style: 'border-radius: 0px;'%>        
      </div>


         

  </div>
</div>

app/views/songs/update.html.erb
<h1>Songs#update</h1>
<p>Find me in app/views/songs/update.html.erb</p>